appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: zGES+R8lMme7+pSZec/93lfn0wcDepU2tlHVVlchcNgXpQgoY3+cpOh6TDjTRAGt7bhqiShvNbE3UU/NOG5VlF6bzSIZOmkAoxsG3kx0Mg//IUHJxd/VG1uDvPhlPLA+TUSPDyHhuoMLnHlI2LYU3hHYrDLVvEnRuBBj/pmY0XtiL26+cnPAGu4Laeepm41bJzEfyKMh1cACWSJFlceJviyI8qJrxUENZWQaM7x+EMnHaj5v7SV4XHiuEV6yzfELTH49yk9Rj0vTldnHG0YFL/Qc/u71BbxLitWi87vuRjwi7GhT7Yt8vyrBQ2te6nN6e4m58zTeDdRaa0sHEcewxB5QArtM+wXjbKGOj0KKB9348e3V+PwPmhKMLOynGLvKbuM4JDDUCMSEv3KVamWR3cTjYpBIHhhG3UKpwplEENidNyX0HOu1pndhsO+UruI9MapsZPNTyap6vudz979z798DjPdlWFrUZDVHH6PCU/lb84Mgs+S4MIvDu9TowHtfkeAlFFihB0d4ZnWsTTflba4DvkI03wHRpHNx1AgjHZJQRQ7YZF0oEOhb1WEaunwxwUL7HYv5B8I/T+M/g+VDnlcpBWbU7wgVS3YWBxcUDMi5YKJ+EIB1am9N/m9M5wMo9fFyyGrw/oaF/4EpKHZqdMuNlYbh1j/Xfx0jrPZRuYY=}
bot:
  automerge: true
